Authentication
re-pesk/simul-doc-be pull request #10
Opened 2018-05-25 13:05 UTC by re-pe

2018-05-25 14:05 UTC, ralekna requested changes
Please comment and ask me if you don't understand something that I say in comments.

2018-05-25 14:05 UTC, ralekna commented on .gitignore
> +.idea/
Thanks! :)

2018-05-25 14:05 UTC, ralekna commented on _init/_init.1.js
> +const USERNO = 5;
What is the meaning of these constants?

2018-05-25 14:05 UTC, ralekna commented on _init/_init.1.js
> +const makeObjectString = (strTempl, variables) => {
I think that the name of this function doesn't correctly represent of what it is doing.

2018-05-25 14:05 UTC, ralekna commented on _init/_init.1.js
> +const User = require("../models/user");
There's a convention to call files that generate test data into database "seed" files. 
So you can have seed.development.js (for use during development),
seed.production.js (for initialization in production environment),
seed.test.js (for use in test environment)

2018-05-25 14:05 UTC, ralekna commented on _init/_init.1.js
> +const makeArrayOfPromises = (model, data) =>
This function is creating and saving new documents into database from a given data. So this should be said in a functions name. What arguments function take and what it returns - should be a responsibility of type signatures (if you're using TypeScript) or JSDoc.

And by the way:
Mongoose has it's own method for inserting many documents at one time:
It's `.create` (when you pass an array of objects) and `.insertMany`.

2018-05-25 14:05 UTC, ralekna commented on _init/_init.1.js
> +  let result = strTempl;
Instead of creating this big function you could use ES6 template literals with interpolation:

```js
let createUserFromTemplate = (userId, index) => JSON.parse(`{
  owner: "${userId}",
  authors: ["${userId}"],
  title: "title${index}",
  content: "content ${index}"
}`);

let userObject = createUserFromTemplate("someUserId", 1);
```

2018-05-25 14:05 UTC, ralekna commented on _init/_init.1.js
> +        return { index: index };
In ES6 you don't have to type value for object key if it has a same name as variable.
So in this case `return {index}` would do the same.

2018-05-25 14:05 UTC, ralekna commented on _init/_init.1.js
> +  console.log(`userIdList(${userIdList.length}) => [${userIdList}]`);
Please remove logs if you're not using them.

2018-05-25 14:05 UTC, ralekna commented on _init/_init.js
> +const User = require("../models/user");
I don't understand why there're two files of `_init`.

2018-05-25 14:05 UTC, ralekna commented on _init/_init.1.js
> +  let makeUserPromiseList = Promise.resolve(db.dropDatabase())
You can use `away` here and get results into variable instead of creating intermediate variables.

2018-05-25 14:13 UTC, re-pe commented on _init/_init.1.js
> +const USERNO = 5;
This is number of users to create.

2018-05-25 14:16 UTC, ralekna commented on _init/_init.1.js
> +const USERNO = 5;
Then please rename it into `NUMBER_OF_USERS_TO_CREATE`. 
Do not save space on readability!

2018-05-28 08:27 UTC, ralekna approved these changes

2018-05-28 08:45 UTC, merged