Validation
re-pesk/simul-doc-be pull request #9
Opened 2018-05-11 12:13 UTC by re-pe

2018-05-11 12:24 UTC, ralekna requested changes

2018-05-11 12:24 UTC, ralekna commented on routes/documents.js
> +const DocumentBodySchema = require('./validators/validators').DocumentBodySchema;
You can use object destructuring here:
`const { DocumentBodySchema } = require('./validators/validators');`

2018-05-11 12:24 UTC, ralekna commented on routes/users.js
> +    console.log(records)
Will you need this?

2018-05-11 12:24 UTC, ralekna commented on routes/users.js
> +    console.log(next)
Will you need this?

2018-05-11 12:24 UTC, ralekna commented on routes/users.js
> +// router.get('/id::usrId;abc::abc', (req, res, next) => {
Do not leave commented out code. 99% of the time commented code will never be used and is a visual trash.

2018-05-11 12:24 UTC, ralekna commented on routes/validators/validators.js
> +    body: Joi.alternatives().try(DocumentValidator, DocumentArrayValidator)
In what cases there will be an array Documents?

2018-05-11 12:24 UTC, ralekna commented on routes/validators/validators.js
> +}
Please leave an empty line at the end of the file. You IDE may have an option to put it automacally.

2018-05-11 12:24 UTC, ralekna commented on routes/validators/validators.js
> +    body: Joi.alternatives().try(UserValidator, UserArrayValidator)
Same as for DocumentsBodySchema

2018-05-14 07:43 UTC, re-pe commented on routes/validators/validators.js
> +    body: Joi.alternatives().try(DocumentValidator, DocumentArrayValidator)
Without it, /documents accepts all array without validation.

2018-05-14 07:44 UTC, re-pe commented on routes/validators/validators.js
> +    body: Joi.alternatives().try(UserValidator, UserArrayValidator)
Same as in case of /documents.

2018-05-14 08:53 UTC, re-pe commented on routes/validators/validators.js
> +    body: Joi.alternatives().try(DocumentValidator, DocumentArrayValidator)
Removed

2018-05-14 08:54 UTC, re-pe commented on routes/validators/validators.js
> +    body: Joi.alternatives().try(UserValidator, UserArrayValidator)
Removed

2018-05-14 08:55 UTC, ralekna approved these changes

2018-05-14 09:08 UTC, merged